/* SmrtDesk Product Data */
var PRODUCTS = {
  'B0B27MDKXD': {
    id: '5-pcs-large-fruit-containers-for-fridge-leakproof-with-removable-colander',
    asin: 'B0B27MDKXD',
    brand: 'Amazon',
    title: '5 PCS Large Fruit Containers for Fridge - Leakproof with Removable Colander',
    titleShort: '5 PCS Large Fruit Containers for Fridge - Leakproof with Removable Colander',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$20.49',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0B27MDKXD.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0B27MDKXD?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'food-storage-container',
    categoryName: 'Food Storage Container',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $20.49', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },

  'B0FDQK69GQ': {
    id: 'ailun-3-pack-screen-protector-for-iphone-17-pro-max-69-inch-with-installation-fr',
    asin: 'B0FDQK69GQ',
    brand: 'Amazon',
    title: 'Ailun 3 Pack Screen Protector for iPhone 17 Pro Max [6.9 inch] with Installation Frame',
    titleShort: 'Ailun 3 Pack Screen Protector for iPhone 17 Pro Max [6.9 inch] with Installation Frame',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$6.98',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0FDQK69GQ.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0FDQK69GQ?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'phone-accessories',
    categoryName: 'Phone Accessories',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $6.98', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0DGXHWWSV': {
    id: 'aknear-led-rechargeable-headlamp-99000-high-lumens',
    asin: 'B0DGXHWWSV',
    brand: 'AKNEAR',
    title: 'AKNEAR LED Rechargeable Headlamp 99000 High Lumens',
    titleShort: 'AKNEAR LED Rechargeable Headlamp 99000 High Lumens',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$19.99',
    rating: '4.4',
    stars: '★★★★☆',
    reviewCount: '3200',
    image: 'product_images/B0DGXHWWSV.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0DGXHWWSV?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'camping-lighting',
    categoryName: 'Camping Lighting',
    pros: ['Rechargeable Headlamp', 'Ultra Bright', 'Motion Sensor', 'Waterproof'],
    cons: ['Check sizing before ordering', 'Price may vary by seller', 'Some assembly may be required']
  },

  'B088NRLMPV': {
    id: 'anker-usb-c-to-usb-c-cable-60w-fast-charging-6-ft-2pack',
    asin: 'B088NRLMPV',
    brand: 'Amazon',
    title: 'Anker USB C to USB C Cable, 60W Fast Charging (6 FT, 2Pack)',
    titleShort: 'Anker USB C to USB C Cable, 60W Fast Charging (6 FT, 2Pack)',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$9.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B088NRLMPV.jpg',
    amazonLink: 'https://www.amazon.com/dp/B088NRLMPV?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'phone-accessories',
    categoryName: 'Phone Accessories',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $9.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0B7JL46ZB': {
    id: 'anxxsu-metal-storage-locker-lockable-employees-locker-55-height-retro-black',
    asin: 'B0B7JL46ZB',
    brand: 'Amazon',
    title: 'Anxxsu Metal Storage Locker, Lockable Employees Locker, 55" Height, Retro Black',
    titleShort: 'Anxxsu Metal Storage Locker, Lockable Employees Locker, 55" Height, Retro Black',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$84.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0B7JL46ZB.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0B7JL46ZB?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'steel-lockers',
    categoryName: 'Steel Lockers',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $84.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0DGHMNQ5Z': {
    id: 'apple-airpods-4-wireless-earbuds-bluetooth-headphones-with-spatial-audio',
    asin: 'B0DGHMNQ5Z',
    brand: 'Amazon',
    title: 'Apple AirPods 4 Wireless Earbuds, Bluetooth Headphones with Spatial Audio',
    titleShort: 'Apple AirPods 4 Wireless Earbuds, Bluetooth Headphones with Spatial Audio',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$138.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0DGHMNQ5Z.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0DGHMNQ5Z?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'phone-accessories',
    categoryName: 'Phone Accessories',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $138.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0GJTFXNRX': {
    id: 'apple-airtag-2nd-generation-tracker-for-keychain-wallet-and-more',
    asin: 'B0GJTFXNRX',
    brand: 'Amazon',
    title: 'Apple AirTag (2nd Generation): Tracker for Keychain, Wallet, and More',
    titleShort: 'Apple AirTag (2nd Generation): Tracker for Keychain, Wallet, and More',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$26.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0GJTFXNRX.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0GJTFXNRX?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'phone-accessories',
    categoryName: 'Phone Accessories',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $26.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0DCH8VDXF': {
    id: 'apple-earpods-headphones-with-usb-c-plug-wired-ear-buds-with-remote',
    asin: 'B0DCH8VDXF',
    brand: 'Amazon',
    title: 'Apple EarPods Headphones with USB-C Plug, Wired Ear Buds with Remote',
    titleShort: 'Apple EarPods Headphones with USB-C Plug, Wired Ear Buds with Remote',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$17.87',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0DCH8VDXF.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0DCH8VDXF?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'phone-accessories',
    categoryName: 'Phone Accessories',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $17.87', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0FKN2SR3L': {
    id: 'babyletto-lido-wave-convertible-low-profile-bunk-bed-twin-white',
    asin: 'B0FKN2SR3L',
    brand: 'Amazon',
    title: 'Babyletto Lido Wave Convertible Low-Profile Bunk Bed, Twin, White',
    titleShort: 'Babyletto Lido Wave Convertible Low-Profile Bunk Bed, Twin, White',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$899.00',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0FKN2SR3L.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0FKN2SR3L?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'loft-bed',
    categoryName: 'Loft Bed',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $899.00', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B09JTHT445': {
    id: 'basics-3-drawer-lockable-mobile-file-cabinet',
    asin: 'B09JTHT445',
    brand: 'Amazon',
    title: 'Basics 3-Drawer Lockable Mobile File Cabinet',
    titleShort: 'Basics 3-Drawer Lockable Mobile File Cabinet',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$72.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B09JTHT445.jpg',
    amazonLink: 'https://www.amazon.com/dp/B09JTHT445?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'filing-cabinet',
    categoryName: 'Filing Cabinet',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $72.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0CQTPZNV8': {
    id: 'basics-adjustable-dual-monitor-desk-mount',
    asin: 'B0CQTPZNV8',
    brand: 'Amazon',
    title: 'Basics Adjustable Dual Monitor Desk Mount',
    titleShort: 'Basics Adjustable Dual Monitor Desk Mount',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$34.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0CQTPZNV8.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0CQTPZNV8?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'monitor-stand',
    categoryName: 'Monitor Stand',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $34.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B081H3Y5NW': {
    id: 'basics-classic-puresoft-pu-padded-mid-back-office-chair',
    asin: 'B081H3Y5NW',
    brand: 'Amazon',
    title: 'Basics Classic Puresoft PU Padded Mid-Back Office Chair',
    titleShort: 'Basics Classic Puresoft PU Padded Mid-Back Office Chair',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$89.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B081H3Y5NW.jpg',
    amazonLink: 'https://www.amazon.com/dp/B081H3Y5NW?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'office-chair',
    categoryName: 'Office Chair',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $89.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0D9XYD75W': {
    id: 'basics-vertical-file-cabinet-2-drawer-letter-size-locking-steel-black',
    asin: 'B0D9XYD75W',
    brand: 'Amazon',
    title: 'Basics Vertical File Cabinet, 2-Drawer, Letter Size, Locking, Steel, Black',
    titleShort: 'Basics Vertical File Cabinet, 2-Drawer, Letter Size, Locking, Steel, Black',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$109.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0D9XYD75W.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0D9XYD75W?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'vertical-file-cabinet',
    categoryName: 'Vertical File Cabinet',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $109.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },

  'B0DDQB78L2': {
    id: 'bolosy-oversized-xl-camping-chair-heavy-duty-500lbs',
    asin: 'B0DDQB78L2',
    brand: 'Bolosy',
    title: 'Bolosy Oversized XL Camping Chair Heavy Duty 500LBS',
    titleShort: 'Bolosy Oversized XL Camping Chair Heavy Duty 500LBS',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$59.99',
    rating: '4.4',
    stars: '★★★★☆',
    reviewCount: '1280',
    image: 'product_images/B0DDQB78L2.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0DDQB78L2?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'camp-furniture',
    categoryName: 'Camp Furniture',
    pros: ['Oversized Padded Chair', 'Heavy Duty 500Lb', 'Cup Holder Cooler Bag', 'Collapsible'],
    cons: ['Check sizing before ordering', 'Price may vary by seller', 'Some assembly may be required']
  },

  'B085KBN2DN': {
    id: 'branch-duo-standing-desk',
    asin: 'B085KBN2DN',
    brand: 'Amazon',
    title: 'Branch Duo Standing Desk',
    titleShort: 'Branch Duo Standing Desk',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$499.00+',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B085KBN2DN.jpg',
    amazonLink: 'https://www.amazon.com/dp/B085KBN2DN?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'standing-desk',
    categoryName: 'Standing Desk',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $499.00+', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0C4XMZP9Y': {
    id: 'branch-ergonomic-chair-pro',
    asin: 'B0C4XMZP9Y',
    brand: 'Amazon',
    title: 'Branch Ergonomic Chair Pro',
    titleShort: 'Branch Ergonomic Chair Pro',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$349.00',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0C4XMZP9Y.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0C4XMZP9Y?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'office-chair',
    categoryName: 'Office Chair',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $349.00', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },

  'B0DSDXBV89': {
    id: 'bthfst-bunk-bed-twin-over-twin-with-stairs-led-lights-2-storage-drawers-and-6',
    asin: 'B0DSDXBV89',
    brand: 'Amazon',
    title: 'BTHFST Bunk Bed Twin Over Twin with Stairs, LED Lights, 2 Storage Drawers & 6 Fabric Drawers, Black',
    titleShort: 'BTHFST Bunk Bed Twin Over Twin with Stairs, LED Lights, 2 Storage Drawers & 6 Fabric Drawers, Black',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$229.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0DSDXBV89.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0DSDXBV89?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'bunk-bed',
    categoryName: 'Bunk Bed',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $229.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0DZT71QKT': {
    id: 'butisow-metal-lockers-66-height-steel-lockers-for-employees-5-doors-gray',
    asin: 'B0DZT71QKT',
    brand: 'Amazon',
    title: 'BUTISOW Metal Lockers - 66" Height Steel Lockers for Employees, 5 Doors, Gray',
    titleShort: 'BUTISOW Metal Lockers - 66" Height Steel Lockers for Employees, 5 Doors, Gray',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$129.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0DZT71QKT.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0DZT71QKT?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'steel-lockers',
    categoryName: 'Steel Lockers',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $129.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0DT3Y1X96': {
    id: 'castlery-seb-executive-desk',
    asin: 'B0DT3Y1X96',
    brand: 'Amazon',
    title: 'Castlery Seb Executive Desk',
    titleShort: 'Castlery Seb Executive Desk',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$899.00',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0DT3Y1X96.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0DT3Y1X96?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'executive-desk',
    categoryName: 'Executive Desk',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $899.00', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },

  'B0F9FXHF5S': {
    id: 'cliq-classiq-2-0-portable-camping-chair',
    asin: 'B0F9FXHF5S',
    brand: 'CLIQ',
    title: 'CLIQ ClassiQ 2.0 Portable Camping Chair',
    titleShort: 'CLIQ ClassiQ 2.0 Portable Camping Chair',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$99.99',
    rating: '4.2',
    stars: '★★★★☆',
    reviewCount: '6825',
    image: 'product_images/B0F9FXHF5S.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0F9FXHF5S?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'camp-furniture',
    categoryName: 'Camp Furniture',
    pros: ['Lightweight Portable Folding Chair', 'Compact Camp Chair', 'Quick Setup', 'Aircraft Aluminum'],
    cons: ['Check sizing before ordering', 'Price may vary by seller', 'Some assembly may be required']
  },
  'B00R2OTYR2': {
    id: 'coaster-home-furnishings-stephan-rustic-metal-full-over-full-bunk-bed-gunmetal',
    asin: 'B00R2OTYR2',
    brand: 'Amazon',
    title: 'Coaster Home Furnishings Stephan Rustic Metal Full Over Full Bunk Bed, Gunmetal',
    titleShort: 'Coaster Home Furnishings Stephan Rustic Metal Full Over Full Bunk Bed, Gunmetal',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$349.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B00R2OTYR2.jpg',
    amazonLink: 'https://www.amazon.com/dp/B00R2OTYR2?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'bunk-bed',
    categoryName: 'Bunk Bed',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $349.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0BD7Z94ZQ': {
    id: 'colamy-ergonomic-office-chair-kirin-series',
    asin: 'B0BD7Z94ZQ',
    brand: 'Amazon',
    title: 'Colamy Ergonomic Office Chair (Kirin Series)',
    titleShort: 'Colamy Ergonomic Office Chair (Kirin Series)',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$279.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0BD7Z94ZQ.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0BD7Z94ZQ?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'office-chair',
    categoryName: 'Office Chair',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $279.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },


  'B00005OU9D': {
    id: 'coleman-classic-2-burner-propane-gas-camping-stove',
    asin: 'B00005OU9D',
    brand: 'Coleman',
    title: 'Coleman Classic 2-Burner Propane Gas Camping Stove',
    titleShort: 'Coleman Classic 2-Burner Propane Gas Camping Stove',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$44.99',
    rating: '4.6',
    stars: '★★★★☆',
    reviewCount: '9600',
    image: 'product_images/B00005OU9D.jpg',
    amazonLink: 'https://www.amazon.com/dp/B00005OU9D?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'camp-cooking',
    categoryName: 'Camp Cooking',
    pros: ['Propane Stove', '2 Burner', '20', '000 Btu'],
    cons: ['Check sizing before ordering', 'Price may vary by seller', 'Some assembly may be required']
  },

  'B004J2GUP4': {
    id: 'coleman-sundome-4-person-camping-tent-with-rainfly',
    asin: 'B004J2GUP4',
    brand: 'Coleman',
    title: 'Coleman Sundome 4-Person Camping Tent with Rainfly',
    titleShort: 'Coleman Sundome 4-Person Camping Tent with Rainfly',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$69.99',
    rating: '4.6',
    stars: '★★★★☆',
    reviewCount: '47972',
    image: 'product_images/B004J2GUP4.jpg',
    amazonLink: 'https://www.amazon.com/dp/B004J2GUP4?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'camping-outdoors',
    categoryName: 'Camping & Outdoors',
    pros: ['Dome Tent', '10 Minute Setup', 'Weatherproof', 'Rainfly Included'],
    cons: ['Check sizing before ordering', 'Price may vary by seller', 'Some assembly may be required']
  },

  'B08G53L8B5': {
    id: 'devaise-2-drawer-metal-file-cabinet-fully-assembled',
    asin: 'B08G53L8B5',
    brand: 'Amazon',
    title: 'DEVAISE 2 Drawer Metal File Cabinet, Fully Assembled',
    titleShort: 'DEVAISE 2 Drawer Metal File Cabinet, Fully Assembled',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$129.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B08G53L8B5.jpg',
    amazonLink: 'https://www.amazon.com/dp/B08G53L8B5?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'filing-cabinet',
    categoryName: 'Filing Cabinet',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $129.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0989HLF81': {
    id: 'devaise-3-drawer-mobile-file-cabinet-wood-lateral',
    asin: 'B0989HLF81',
    brand: 'Amazon',
    title: 'DEVAISE 3 Drawer Mobile File Cabinet, Wood Lateral',
    titleShort: 'DEVAISE 3 Drawer Mobile File Cabinet, Wood Lateral',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$94.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0989HLF81.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0989HLF81?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'filing-cabinet',
    categoryName: 'Filing Cabinet',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $94.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },

  'B0C8HBFNMV': {
    id: 'dhp-metal-loft-bed-twin-size-with-desk-and-bookshelf-silver',
    asin: 'B0C8HBFNMV',
    brand: 'Amazon',
    title: 'DHP Metal Loft Bed Twin Size with Desk and Bookshelf, Silver',
    titleShort: 'DHP Metal Loft Bed Twin Size with Desk and Bookshelf, Silver',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$249.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0C8HBFNMV.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0C8HBFNMV?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'loft-bed',
    categoryName: 'Loft Bed',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $249.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0CMWQMF16': {
    id: 'dhp-twin-over-full-bunk-bed-with-ladder-and-guardrails-metal-frame-black',
    asin: 'B0CMWQMF16',
    brand: 'Amazon',
    title: 'DHP Twin Over Full Bunk Bed with Ladder and Guardrails, Metal Frame, Black',
    titleShort: 'DHP Twin Over Full Bunk Bed with Ladder and Guardrails, Metal Frame, Black',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$179.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0CMWQMF16.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0CMWQMF16?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'bunk-bed',
    categoryName: 'Bunk Bed',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $179.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B09Q2Y62ZM': {
    id: 'echosmile-instant-pop-up-2-person-camping-tent',
    asin: 'B09Q2Y62ZM',
    brand: 'EchoSmile',
    title: 'EchoSmile Instant Pop Up 2-Person Camping Tent',
    titleShort: 'EchoSmile Instant Pop Up 2-Person Camping Tent',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$81.99',
    rating: '4.1',
    stars: '★★★★☆',
    reviewCount: '3955',
    image: 'product_images/B09Q2Y62ZM.jpg',
    amazonLink: 'https://www.amazon.com/dp/B09Q2Y62ZM?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'camping-outdoors',
    categoryName: 'Camping & Outdoors',
    pros: ['Pop Up Tent', 'Instant Setup', 'Water Resistant', '2 Person'],
    cons: ['Check sizing before ordering', 'Price may vary by seller', 'Some assembly may be required']
  },
  'B0G8JBLM77': {
    id: 'elegear-cumbrex-4-thick-self-inflating-sleeping-pad',
    asin: 'B0G8JBLM77',
    brand: 'Elegear',
    title: 'Elegear CumbreX 4 inch Thick Self-Inflating Sleeping Pad',
    titleShort: 'Elegear CumbreX 4 inch Thick Self-Inflating Sleeping Pad',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$69.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '3800',
    image: 'product_images/B0G8JBLM77.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0G8JBLM77?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'sleeping-gear',
    categoryName: 'Sleeping Gear',
    pros: ['Self-Inflating Pad', '9.5 R-Value', '4 Season', 'Insulated'],
    cons: ['Check sizing before ordering', 'Price may vary by seller', 'Some assembly may be required']
  },
  'B082MLVXRR': {
    id: 'ergear-dual-monitor-stand-heavy-duty',
    asin: 'B082MLVXRR',
    brand: 'Amazon',
    title: 'ErGear Dual Monitor Stand Heavy Duty',
    titleShort: 'ErGear Dual Monitor Stand Heavy Duty',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$28.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B082MLVXRR.jpg',
    amazonLink: 'https://www.amazon.com/dp/B082MLVXRR?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'monitor-stand',
    categoryName: 'Monitor Stand',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $28.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0B41YH9B6': {
    id: 'ergear-height-adjustable-electric-standing-desk-48x24',
    asin: 'B0B41YH9B6',
    brand: 'Amazon',
    title: 'ErGear Height Adjustable Electric Standing Desk 48x24',
    titleShort: 'ErGear Height Adjustable Electric Standing Desk 48x24',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$219.99+',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0B41YH9B6.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0B41YH9B6?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'standing-desk',
    categoryName: 'Standing Desk',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $219.99+', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0FQM6QB48': {
    id: 'ergear-single-monitor-arm-fully-adjustable-for-13-34-inch-screens',
    asin: 'B0FQM6QB48',
    brand: 'Amazon',
    title: 'ErGear Single Monitor Arm, Fully Adjustable for 13-34 Inch Screens',
    titleShort: 'ErGear Single Monitor Arm, Fully Adjustable for 13-34 Inch Screens',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$20.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0FQM6QB48.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0FQM6QB48?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'monitor-stand',
    categoryName: 'Monitor Stand',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $20.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0CG1ZHD74': {
    id: 'eureka-ark-es-executive-standing-desk',
    asin: 'B0CG1ZHD74',
    brand: 'Superday',
    title: 'Superday Metal Storage Cabinet, 72" Garage Storage Cabinets with Lock',
    titleShort: 'Superday Metal Storage Cabinet, 72" Garage Storage Cabinets with Lock',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$799.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0CG1ZHD74.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0CG1ZHD74?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'steel-lockers',
    categoryName: 'Steel Lockers',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $799.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0DJ2XKJJT': {
    id: 'flexispot-en1-one-piece-standing-desk',
    asin: 'B0DJ2XKJJT',
    brand: 'Amazon',
    title: 'FlexiSpot EN1 One-Piece Standing Desk',
    titleShort: 'FlexiSpot EN1 One-Piece Standing Desk',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$299.99+',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0DJ2XKJJT.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0DJ2XKJJT?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'standing-desk',
    categoryName: 'Standing Desk',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $299.99+', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },

  'B081DFLV9K': {
    id: 'freshware-food-storage-containers-50-set-16-oz-plastic-deli-containers-with-lids',
    asin: 'B081DFLV9K',
    brand: 'Amazon',
    title: 'Freshware Food Storage Containers [50 Set] 16 oz Plastic Deli Containers with Lids',
    titleShort: 'Freshware Food Storage Containers [50 Set] 16 oz Plastic Deli Containers with Lids',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$17.50',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B081DFLV9K.jpg',
    amazonLink: 'https://www.amazon.com/dp/B081DFLV9K?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'food-storage-container',
    categoryName: 'Food Storage Container',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $17.50', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B07Y8BXBX8': {
    id: 'gabrylly-ergonomic-office-chair-high-back',
    asin: 'B07Y8BXBX8',
    brand: 'Amazon',
    title: 'GABRYLLY Ergonomic Office Chair High Back',
    titleShort: 'GABRYLLY Ergonomic Office Chair High Back',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$169.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B07Y8BXBX8.jpg',
    amazonLink: 'https://www.amazon.com/dp/B07Y8BXBX8?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'office-chair',
    categoryName: 'Office Chair',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $169.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },


  'B01LYBQXRH': {
    id: 'gladiator-premier-3-piece-garage-cabinet-set-silver-metallic',
    asin: 'B01LYBQXRH',
    brand: 'Amazon',
    title: 'Gladiator Premier 3-Piece Garage Cabinet Set, Silver Metallic',
    titleShort: 'Gladiator Premier 3-Piece Garage Cabinet Set, Silver Metallic',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$1,648.00',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B01LYBQXRH.jpg',
    amazonLink: 'https://www.amazon.com/dp/B01LYBQXRH?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'garage-cabinets',
    categoryName: 'Garage Cabinets',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $1,648.00', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B07773PQG7': {
    id: 'gorilla-grip-powergrip-drawer-shelf-and-cabinet-liner-12-x-20',
    asin: 'B07773PQG7',
    brand: 'Amazon',
    title: 'GORILLA GRIP powerGRIP Drawer Shelf and Cabinet Liner, 12" x 20\'',
    titleShort: 'GORILLA GRIP powerGRIP Drawer Shelf and Cabinet Liner, 12" x 20\'',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$19.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B07773PQG7.jpg',
    amazonLink: 'https://www.amazon.com/dp/B07773PQG7?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'kitchen-storage-organizer',
    categoryName: 'Kitchen Storage Furniture',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $19.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },

  'B0FPM4NYR5': {
    id: 'homary-executive-desk-stationary',
    asin: 'B0FPM4NYR5',
    brand: 'INTERGREAT',
    title: 'INTERGREAT Metal Storage Cabinet with Doors, 72" Locking Steel Storage Cabinet',
    titleShort: 'INTERGREAT Metal Storage Cabinet with Doors, 72" Locking Steel Storage Cabinet',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$519.99+',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0FPM4NYR5.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0FPM4NYR5?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'steel-lockers',
    categoryName: 'Steel Lockers',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $519.99+', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0FFSBVFMP': {
    id: 'homhedy-farmhouse-bathroom-storage-cabinet-with-2-doors-white',
    asin: 'B0FFSBVFMP',
    brand: 'Amazon',
    title: 'Homhedy Farmhouse Bathroom Storage Cabinet with 2 Doors, White',
    titleShort: 'Homhedy Farmhouse Bathroom Storage Cabinet with 2 Doors, White',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$79.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0FFSBVFMP.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0FFSBVFMP?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'storage-shelves',
    categoryName: 'Storage Shelves',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $79.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B07FLC2YDF': {
    id: 'hon-2-drawer-vertical-file-cabinet-letter-size-locking-putty',
    asin: 'B07FLC2YDF',
    brand: 'Amazon',
    title: 'HON 2-Drawer Vertical File Cabinet, Letter Size, Locking, Putty',
    titleShort: 'HON 2-Drawer Vertical File Cabinet, Letter Size, Locking, Putty',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$299.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B07FLC2YDF.jpg',
    amazonLink: 'https://www.amazon.com/dp/B07FLC2YDF?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'vertical-file-cabinet',
    categoryName: 'Vertical File Cabinet',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $299.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B07T5SY43L': {
    id: 'huanuo-flowlift-dual-monitor-stand',
    asin: 'B07T5SY43L',
    brand: 'Amazon',
    title: 'HUANUO FlowLift—Dual Monitor Stand',
    titleShort: 'HUANUO FlowLift—Dual Monitor Stand',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$39.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B07T5SY43L.jpg',
    amazonLink: 'https://www.amazon.com/dp/B07T5SY43L?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'monitor-stand',
    categoryName: 'Monitor Stand',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $39.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0GK7FVTR4': {
    id: 'huanuo-flowlift-pro-monitor-arm-for-13-32-screens-mechaspring',
    asin: 'B0GK7FVTR4',
    brand: 'Amazon',
    title: 'HUANUO FlowLift Pro Monitor Arm for 13-32" Screens, MechaSpring',
    titleShort: 'HUANUO FlowLift Pro Monitor Arm for 13-32" Screens, MechaSpring',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$26.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0GK7FVTR4.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0GK7FVTR4?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'monitor-stand',
    categoryName: 'Monitor Stand',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $26.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B07T3KCQ94': {
    id: 'huanuo-flowlift-single-monitor-mount-for-13-to-32-inch-screens',
    asin: 'B07T3KCQ94',
    brand: 'Amazon',
    title: 'HUANUO FlowLift Single Monitor Mount for 13 to 32 Inch Screens',
    titleShort: 'HUANUO FlowLift Single Monitor Mount for 13 to 32 Inch Screens',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$47.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B07T3KCQ94.jpg',
    amazonLink: 'https://www.amazon.com/dp/B07T3KCQ94?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'laptop-accessories',
    categoryName: 'Laptop Accessories',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $47.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },

  'B0CB1FW5FC': {
    id: 'iniu-45w-fast-charging-portable-charger-10000mah-with-detachable-cable',
    asin: 'B0CB1FW5FC',
    brand: 'Amazon',
    title: 'INIU 45W Fast Charging Portable Charger, 10000mAh with Detachable Cable',
    titleShort: 'INIU 45W Fast Charging Portable Charger, 10000mAh with Detachable Cable',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$19.50',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0CB1FW5FC.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0CB1FW5FC?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'phone-accessories',
    categoryName: 'Phone Accessories',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $19.50', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0C4T3RQQC': {
    id: 'intergreat-metal-storage-cabinet-with-lock-72-h-lockable-steel-cabinet-black',
    asin: 'B0C4T3RQQC',
    brand: 'Amazon',
    title: 'INTERGREAT Metal Storage Cabinet with Lock, 72" H Lockable Steel Cabinet, Black',
    titleShort: 'INTERGREAT Metal Storage Cabinet with Lock, 72" H Lockable Steel Cabinet, Black',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$149.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0C4T3RQQC.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0C4T3RQQC?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'steel-lockers',
    categoryName: 'Steel Lockers',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $149.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0B283QP2N': {
    id: 'iphone-charger-fast-charging-2-pack-type-c-wall-charger-block-with-2-pack-6ftand',
    asin: 'B0B283QP2N',
    brand: 'Amazon',
    title: 'iPhone Charger Fast Charging 2 Pack Type C Wall Charger Block with 2 Pack [6FT&10FT] Long USB C to Lightning Cable',
    titleShort: 'iPhone Charger Fast Charging 2 Pack Type C Wall Charger Block with 2 Pack [6FT&10FT] Long USB C to Lightning Cable',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$9.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0B283QP2N.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0B283QP2N?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'phone-accessories',
    categoryName: 'Phone Accessories',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $9.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B08ZCTL5HC': {
    id: 'iwell-67-tall-bathroom-cabinet-2-doors-and-1-drawer-white',
    asin: 'B08ZCTL5HC',
    brand: 'Amazon',
    title: 'Iwell 67" Tall Bathroom Cabinet, 2 Doors & 1 Drawer, White',
    titleShort: 'Iwell 67" Tall Bathroom Cabinet, 2 Doors & 1 Drawer, White',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$119.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B08ZCTL5HC.jpg',
    amazonLink: 'https://www.amazon.com/dp/B08ZCTL5HC?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'storage-shelves',
    categoryName: 'Storage Shelves',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $119.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0GS5GJ14G': {
    id: 'jocoevol-metal-bunk-bed-twin-over-twin-with-storage-staircase-clothes-rack-led-w',
    asin: 'B0GS5GJ14G',
    brand: 'Amazon',
    title: 'Jocoevol Metal Bunk Bed Twin Over Twin with Storage Staircase, Clothes Rack, LED, White',
    titleShort: 'Jocoevol Metal Bunk Bed Twin Over Twin with Storage Staircase, Clothes Rack, LED, White',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$259.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0GS5GJ14G.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0GS5GJ14G?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'bunk-bed',
    categoryName: 'Bunk Bed',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $259.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0B4K1XH8Y': {
    id: 'kitsure-dish-drying-rack-for-kitchen-counter-stainless-steel',
    asin: 'B0B4K1XH8Y',
    brand: 'Amazon',
    title: 'Kitsure Dish Drying Rack for Kitchen Counter, Stainless Steel',
    titleShort: 'Kitsure Dish Drying Rack for Kitchen Counter, Stainless Steel',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$24.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0B4K1XH8Y.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0B4K1XH8Y?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'kitchen-utensils-gadgets',
    categoryName: 'Kitchen Organizer',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $24.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B09YVJN8R7': {
    id: 'letaya-3-drawer-mobile-file-cabinet-with-lock',
    asin: 'B09YVJN8R7',
    brand: 'Amazon',
    title: 'Letaya 3 Drawer Mobile File Cabinet with Lock',
    titleShort: 'Letaya 3 Drawer Mobile File Cabinet with Lock',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$99.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B09YVJN8R7.jpg',
    amazonLink: 'https://www.amazon.com/dp/B09YVJN8R7?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'filing-cabinet',
    categoryName: 'Filing Cabinet',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $99.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0C39QL3XY': {
    id: 'letaya-metal-storage-cabinet-with-lock-72-tall-steel-tool-organizer-black',
    asin: 'B0C39QL3XY',
    brand: 'Amazon',
    title: 'Letaya Metal Storage Cabinet with Lock, 72" Tall Steel Tool Organizer, Black',
    titleShort: 'Letaya Metal Storage Cabinet with Lock, 72" Tall Steel Tool Organizer, Black',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$199.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0C39QL3XY.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0C39QL3XY?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'steel-lockers',
    categoryName: 'Steel Lockers',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $199.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0F8HFLNQG': {
    id: 'lifewit-expandable-silverware-organizer-plastic-utensil-tray-for-kitchen-drawer',
    asin: 'B0F8HFLNQG',
    brand: 'Amazon',
    title: 'Lifewit Expandable Silverware Organizer, Plastic Utensil Tray for Kitchen Drawer',
    titleShort: 'Lifewit Expandable Silverware Organizer, Plastic Utensil Tray for Kitchen Drawer',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$8.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0F8HFLNQG.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0F8HFLNQG?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'kitchen-utensils-gadgets',
    categoryName: 'Kitchen Organizer',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $8.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0GXCJ1QYD': {
    id: 'mixcous-full-over-full-bunk-bed-for-adults-heavy-duty-metal-frame-convertible-to',
    asin: 'B0GXCJ1QYD',
    brand: 'Amazon',
    title: 'Mixcous Full Over Full Bunk Bed for Adults, Heavy Duty Metal Frame, Convertible to 2 Beds, Black',
    titleShort: 'Mixcous Full Over Full Bunk Bed for Adults, Heavy Duty Metal Frame, Convertible to 2 Beds, Black',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$209.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0GXCJ1QYD.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0GXCJ1QYD?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'heavy-duty-bunk',
    categoryName: 'Heavy Duty Bunk',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $209.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },

  'B0814MM9XV': {
    id: 'muscle-rack-4-shelf-unit-with-sides-and-back-steel-black',
    asin: 'B0814MM9XV',
    brand: 'Amazon',
    title: 'Muscle Rack 4-Shelf Unit with Sides and Back, Steel, Black',
    titleShort: 'Muscle Rack 4-Shelf Unit with Sides and Back, Steel, Black',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$149.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0814MM9XV.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0814MM9XV?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'garage-cabinets',
    categoryName: 'Garage Cabinets',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $149.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0C49H4BLG': {
    id: 'newage-products-bold-3-piece-garage-cabinet-set-satin-gray',
    asin: 'B0C49H4BLG',
    brand: 'Amazon',
    title: 'NewAge Products Bold 3-Piece Garage Cabinet Set, Satin Gray',
    titleShort: 'NewAge Products Bold 3-Piece Garage Cabinet Set, Satin Gray',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$1,399.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0C49H4BLG.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0C49H4BLG?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'garage-cabinets',
    categoryName: 'Garage Cabinets',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $1,399.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0F5PPDTVR': {
    id: 'opnice-desk-organizers-and-accessories-dual-monitor-stand-riser-with-drawer-and-',
    asin: 'B0F5PPDTVR',
    brand: 'Amazon',
    title: 'OPNICE Desk Organizers and Accessories, Dual Monitor Stand Riser with Drawer and 2 Pen Holders',
    titleShort: 'OPNICE Desk Organizers and Accessories, Dual Monitor Stand Riser with Drawer and 2 Pen Holders',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$24.31',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0F5PPDTVR.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0F5PPDTVR?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'monitor-stand',
    categoryName: 'Monitor Stand',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $24.31', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B09DKH8XDS': {
    id: 'paper-towel-holder-black-premium-stainless-steel-kitchen-roll-dispenser-countert',
    asin: 'B09DKH8XDS',
    brand: 'Amazon',
    title: 'Paper Towel Holder Black, Premium Stainless Steel Kitchen Roll Dispenser, Countertop with Weighted Base',
    titleShort: 'Paper Towel Holder Black, Premium Stainless Steel Kitchen Roll Dispenser, Countertop with Weighted Base',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$8.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B09DKH8XDS.jpg',
    amazonLink: 'https://www.amazon.com/dp/B09DKH8XDS?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'countertop-storage-rack',
    categoryName: 'Countertop Storage Rack',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $8.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0DPSJP47V': {
    id: 'paper-towel-holder-countertop-standing-paper-roll-holder-with-anti-slip-weighted',
    asin: 'B0DPSJP47V',
    brand: 'Amazon',
    title: 'Paper Towel Holder Countertop, Standing Paper Roll Holder with Anti Slip Weighted Base, Stainless Steel Freestanding Paper Towel Holder for Kitchen',
    titleShort: 'Paper Towel Holder Countertop, Standing Paper Roll Holder with Anti Slip Weighted Base, Stainless Steel Freestanding Paper Towel Holder for Kitchen',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$9.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0DPSJP47V.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0DPSJP47V?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'countertop-storage-rack',
    categoryName: 'Small Accessories',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $9.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0CC27124P': {
    id: 'paper-towel-holder-self-adhesive-or-drilling-under-cabinet-mount-stainless-steel',
    asin: 'B0CC27124P',
    brand: 'Amazon',
    title: 'Paper Towel Holder, Self Adhesive or Drilling Under Cabinet Mount, Stainless Steel',
    titleShort: 'Paper Towel Holder, Self Adhesive or Drilling Under Cabinet Mount, Stainless Steel',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$7.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0CC27124P.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0CC27124P?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'countertop-storage-rack',
    categoryName: 'Countertop Storage Rack',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $7.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },


  'B0DTFHC4NC': {
    id: 'redcamp-10-x10-instant-canopy-tent-with-sidewalls',
    asin: 'B0DTFHC4NC',
    brand: 'REDCAMP',
    title: 'REDCAMP 10\'x10\' Instant Canopy Tent with Sidewalls',
    titleShort: 'REDCAMP 10\'x10\' Instant Canopy Tent with Sidewalls',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$119.99',
    rating: '4.3',
    stars: '★★★★☆',
    reviewCount: '2100',
    image: 'product_images/B0DTFHC4NC.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0DTFHC4NC?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'camping-outdoors',
    categoryName: 'Camping & Outdoors',
    pros: ['Pop Up Canopy', '10X10', 'Uv Protection', 'Sandbags Included'],
    cons: ['Check sizing before ordering', 'Price may vary by seller', 'Some assembly may be required']
  },
  'B08BR9HBZ3': {
    id: 'rubbermaid-brilliance-glass-food-storage-containers-assorted-sizes-set-of-9',
    asin: 'B08BR9HBZ3',
    brand: 'Amazon',
    title: 'Rubbermaid Brilliance Glass Food Storage Containers, Assorted Sizes, Set of 9',
    titleShort: 'Rubbermaid Brilliance Glass Food Storage Containers, Assorted Sizes, Set of 9',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$80.00',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B08BR9HBZ3.jpg',
    amazonLink: 'https://www.amazon.com/dp/B08BR9HBZ3?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'food-storage-container',
    categoryName: 'Food Storage Container',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $80.00', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B079M8FPTW': {
    id: 'rubbermaid-brilliance-tritan-plastic-food-storage-containers-set-of-5-32-cup',
    asin: 'B079M8FPTW',
    brand: 'Amazon',
    title: 'Rubbermaid Brilliance Tritan Plastic Food Storage Containers Set of 5 (3.2 Cup)',
    titleShort: 'Rubbermaid Brilliance Tritan Plastic Food Storage Containers Set of 5 (3.2 Cup)',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$24.58',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B079M8FPTW.jpg',
    amazonLink: 'https://www.amazon.com/dp/B079M8FPTW?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'food-storage-container',
    categoryName: 'Food Storage Container',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $24.58', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B01M0QM2O7': {
    id: 'sauder-select-storage-cabinet-pantry-cabinet-white-finish',
    asin: 'B01M0QM2O7',
    brand: 'Amazon',
    title: 'Sauder Select Storage Cabinet, Pantry Cabinet, White Finish',
    titleShort: 'Sauder Select Storage Cabinet, Pantry Cabinet, White Finish',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$219.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B01M0QM2O7.jpg',
    amazonLink: 'https://www.amazon.com/dp/B01M0QM2O7?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'storage-shelves',
    categoryName: 'Storage Shelves',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $219.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B07GNDDNMW': {
    id: 'sihoo-m18-ergonomic-office-chair',
    asin: 'B07GNDDNMW',
    brand: 'Amazon',
    title: 'SIHOO M18 Ergonomic Office Chair',
    titleShort: 'SIHOO M18 Ergonomic Office Chair',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$259.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B07GNDDNMW.jpg',
    amazonLink: 'https://www.amazon.com/dp/B07GNDDNMW?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'office-chair',
    categoryName: 'Office Chair',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $259.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B09PRGXY3Y': {
    id: 'sikadeer-under-sink-mat-waterproof-34-x-22-silicone-mat-cabinet-liner',
    asin: 'B09PRGXY3Y',
    brand: 'Amazon',
    title: 'SIKADEER Under Sink Mat Waterproof 34" x 22", Silicone Mat Cabinet Liner',
    titleShort: 'SIKADEER Under Sink Mat Waterproof 34" x 22", Silicone Mat Cabinet Liner',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$15.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B09PRGXY3Y.jpg',
    amazonLink: 'https://www.amazon.com/dp/B09PRGXY3Y?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'kitchen-storage-organizer',
    categoryName: 'Kitchen Storage Furniture',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $15.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },

  'B0C7L373XM': {
    id: 'simple-houseware-desk-dual-monitor-stand-riser-with-drawer-rustic-brown',
    asin: 'B0C7L373XM',
    brand: 'Simple',
    title: 'Simple Houseware Desk Dual Monitor Stand Riser with Drawer, - Expert Review | SmrtDesk',
    titleShort: 'Simple Houseware Desk Dual Monitor Stand Riser with Drawer, - Expert Review | SmrtDesk',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$99.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0C7L373XM.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0C7L373XM?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'monitor-stand',
    categoryName: 'Monitor Stand',
    pros: ['Durable construction', 'Great value', 'Highly rated', 'Easy to use'],
    cons: ['Check sizing before ordering', 'Price may vary by seller', 'Some assembly may be required']
  },
  'B07Q79ZZJ6': {
    id: 'single-lcd-computer-monitor-free-standing-desk-stand-mount-riser-for-13-32-inch-',
    asin: 'B07Q79ZZJ6',
    brand: 'Amazon',
    title: 'Single LCD Computer Monitor Free-Standing Desk Stand Mount Riser for 13-32 inch (HT05B-001)',
    titleShort: 'Single LCD Computer Monitor Free-Standing Desk Stand Mount Riser for 13-32 inch (HT05B-001)',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$21.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B07Q79ZZJ6.jpg',
    amazonLink: 'https://www.amazon.com/dp/B07Q79ZZJ6?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'monitor-stand',
    categoryName: 'Monitor Stand',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $21.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0D6SX8VLQ': {
    id: 'smart-speaker-dot-max-newest-model-room-filling-sound-with-nearly-3x-bass',
    asin: 'B0D6SX8VLQ',
    brand: 'Amazon',
    title: 'Premium Smart Speaker with Alexa - Room-filling sound',
    titleShort: 'Premium Smart Speaker with Alexa - Room-filling sound',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$99.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0D6SX8VLQ.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0D6SX8VLQ?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'smart-home-gadgets',
    categoryName: 'Smart Home Gadgets',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $99.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B09B8V1LZ3': {
    id: 'smart-speaker-dot-newest-model-vibrant-sounding-speaker-designed-for-alexa',
    asin: 'B09B8V1LZ3',
    brand: 'Amazon',
    title: 'Smart Speaker with Alexa - Vibrant sounding, Designed for Alexa+',
    titleShort: 'Smart Speaker with Alexa - Vibrant sounding, Designed for Alexa+',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$49.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B09B8V1LZ3.jpg',
    amazonLink: 'https://www.amazon.com/dp/B09B8V1LZ3?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'smart-home-gadgets',
    categoryName: 'Smart Home Gadgets',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $49.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B09B2SBHQK': {
    id: 'smart-speaker-show-5-newest-model-smart-display-with-2x-bass',
    asin: 'B09B2SBHQK',
    brand: 'Amazon',
    title: 'Compact Smart Display with Alexa - 2x bass',
    titleShort: 'Compact Smart Display with Alexa - 2x bass',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$89.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B09B2SBHQK.jpg',
    amazonLink: 'https://www.amazon.com/dp/B09B2SBHQK?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'smart-home-gadgets',
    categoryName: 'Smart Home Gadgets',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $89.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0BLS3QJTX': {
    id: 'smart-speaker-show-8-spatial-audio-smart-home-hub',
    asin: 'B0BLS3QJTX',
    brand: 'Amazon',
    title: 'Smart Display with Alexa, Spatial Audio, Smart Home Hub',
    titleShort: 'Smart Display with Alexa, Spatial Audio, Smart Home Hub',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$112.49',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0BLS3QJTX.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0BLS3QJTX?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'smart-home-gadgets',
    categoryName: 'Smart Home Gadgets',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $112.49', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0BFC7WQ6R': {
    id: 'smart-speaker-spot-newest-model-smart-alarm-clock-designed-for-alexa',
    asin: 'B0BFC7WQ6R',
    brand: 'Amazon',
    title: 'Smart Alarm Clock with Alexa - Designed for Alexa+',
    titleShort: 'Smart Alarm Clock with Alexa - Designed for Alexa+',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$79.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0BFC7WQ6R.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0BFC7WQ6R?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'smart-home-gadgets',
    categoryName: 'Smart Home Gadgets',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $79.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0FF4KTKZL': {
    id: 'sntd-dish-drying-rack-space-saving-dish-rack-for-kitchen-counter-with-utensil-ho',
    asin: 'B0FF4KTKZL',
    brand: 'Amazon',
    title: 'SNTD Dish Drying Rack - Space-Saving Dish Rack for Kitchen Counter with Utensil Holder and Drainboard',
    titleShort: 'SNTD Dish Drying Rack - Space-Saving Dish Rack for Kitchen Counter with Utensil Holder and Drainboard',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$22.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0FF4KTKZL.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0FF4KTKZL?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'kitchen-utensils-gadgets',
    categoryName: 'Kitchen Organizer',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $22.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },


  'B005188T90': {
    id: 'stanley-adventure-even-heat-camp-pro-cook-set',
    asin: 'B005188T90',
    brand: 'Stanley',
    title: 'Stanley Adventure Even-Heat Camp Pro Cook Set',
    titleShort: 'Stanley Adventure Even-Heat Camp Pro Cook Set',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$44.99',
    rating: '4.6',
    stars: '★★★★☆',
    reviewCount: '7800',
    image: 'product_images/B005188T90.jpg',
    amazonLink: 'https://www.amazon.com/dp/B005188T90?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'camp-cooking',
    categoryName: 'Camp Cooking',
    pros: ['Camp Cook Set', 'Stainless Steel', 'Even-Heat Bottom', 'Nesting'],
    cons: ['Check sizing before ordering', 'Price may vary by seller', 'Some assembly may be required']
  },
  'B01H48094C': {
    id: 'sterilite-4-shelf-cabinet-lockable-utility-storage-gray',
    asin: 'B01H48094C',
    brand: 'Amazon',
    title: 'Sterilite 4-Shelf Cabinet, Lockable Utility Storage, Gray',
    titleShort: 'Sterilite 4-Shelf Cabinet, Lockable Utility Storage, Gray',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$89.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B01H48094C.jpg',
    amazonLink: 'https://www.amazon.com/dp/B01H48094C?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'storage-shelves',
    categoryName: 'Storage Shelves',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $89.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },

  'B0FJQDLXXM': {
    id: 'supeer-6-door-metal-storage-locker-heavy-duty-steel-school-locker-72-h-x-354-w-r',
    asin: 'B0FJQDLXXM',
    brand: 'Amazon',
    title: 'SUPEER 6-Door Metal Storage Locker, Heavy Duty Steel School Locker, 72" H x 35.4" W, Red',
    titleShort: 'SUPEER 6-Door Metal Storage Locker, Heavy Duty Steel School Locker, 72" H x 35.4" W, Red',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$229.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0FJQDLXXM.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0FJQDLXXM?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'steel-lockers',
    categoryName: 'Steel Lockers',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $229.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0C8MGJD1F': {
    id: 'tallsen-garage-storage-cabinet-with-lock-heavy-duty-steel-71-x-31-x-15-black',
    asin: 'B0C8MGJD1F',
    brand: 'Amazon',
    title: 'Tallsen Garage Storage Cabinet with Lock, Heavy Duty Steel, 71" x 31" x 15", Black',
    titleShort: 'Tallsen Garage Storage Cabinet with Lock, Heavy Duty Steel, 71" x 31" x 15", Black',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$259.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0C8MGJD1F.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0C8MGJD1F?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'garage-cabinets',
    categoryName: 'Garage Cabinets',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $259.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },

  'B0FNWM5WW8': {
    id: 'ukeetap-extra-thick-silicone-mat-waterproof-with-raised-edge-34-x-22',
    asin: 'B0FNWM5WW8',
    brand: 'Amazon',
    title: 'ukeetap Extra Thick Silicone Mat Waterproof with Raised Edge 34" x 22"',
    titleShort: 'ukeetap Extra Thick Silicone Mat Waterproof with Raised Edge 34" x 22"',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$12.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0FNWM5WW8.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0FNWM5WW8?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'kitchen-storage-organizer',
    categoryName: 'Kitchen Storage Furniture',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $12.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0DNTQ2YNT': {
    id: 'ukeetap-multi-purpose-pull-out-storage-organizers-under-sink-cabinet-2-packs',
    asin: 'B0DNTQ2YNT',
    brand: 'Amazon',
    title: 'Ukeetap Multi-Purpose Pull-Out Storage Organizers, Under Sink/Cabinet, 2 Packs',
    titleShort: 'Ukeetap Multi-Purpose Pull-Out Storage Organizers, Under Sink/Cabinet, 2 Packs',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$16.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0DNTQ2YNT.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0DNTQ2YNT?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'kitchen-storage-organizer',
    categoryName: 'Kitchen Storage Furniture',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $16.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0BHS4PNPL': {
    id: 'uplift-v3-standing-desk',
    asin: 'B0BHS4PNPL',
    brand: 'Amazon',
    title: 'UPLIFT V3 Standing Desk',
    titleShort: 'UPLIFT V3 Standing Desk',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$599.00+',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0BHS4PNPL.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0BHS4PNPL?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'standing-desk',
    categoryName: 'Standing Desk',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $599.00+', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0BRXQ1DKF': {
    id: 'vasagle-2-drawer-file-cabinet-rolling',
    asin: 'B0BRXQ1DKF',
    brand: 'Amazon',
    title: 'VASAGLE 2-Drawer File Cabinet, Rolling',
    titleShort: 'VASAGLE 2-Drawer File Cabinet, Rolling',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$52.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0BRXQ1DKF.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0BRXQ1DKF?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'filing-cabinet',
    categoryName: 'Filing Cabinet',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $52.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0FF4STK4S': {
    id: 'vasagle-storage-cabinet-with-drawers-freestanding-floor-cabinet-cloud-white',
    asin: 'B0FF4STK4S',
    brand: 'Amazon',
    title: 'VASAGLE Storage Cabinet with Drawers, Freestanding Floor Cabinet, Cloud White',
    titleShort: 'VASAGLE Storage Cabinet with Drawers, Freestanding Floor Cabinet, Cloud White',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$79.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0FF4STK4S.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0FF4STK4S?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'storage-shelves',
    categoryName: 'Storage Shelves',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $79.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },

  'B009S750LA': {
    id: 'vivo-dual-monitor-desk-mount-stand-v002',
    asin: 'B009S750LA',
    brand: 'Amazon',
    title: 'VIVO Dual Monitor Desk Mount STAND-V002',
    titleShort: 'VIVO Dual Monitor Desk Mount STAND-V002',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$34.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B009S750LA.jpg',
    amazonLink: 'https://www.amazon.com/dp/B009S750LA?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'monitor-stand',
    categoryName: 'Monitor Stand',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $34.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0D7P6XKNP': {
    id: 'vtopmart-5-pack-22oz-glass-storage-containers-with-lids',
    asin: 'B0D7P6XKNP',
    brand: 'Amazon',
    title: 'Vtopmart 5 Pack 22oz Glass Storage Containers with Lids',
    titleShort: 'Vtopmart 5 Pack 22oz Glass Storage Containers with Lids',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$23.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0D7P6XKNP.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0D7P6XKNP?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'food-storage-container',
    categoryName: 'Food Storage Container',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $23.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0CXWX4XY3': {
    id: 'vtoy-portable-camping-chair-with-canopy-sun-shade',
    asin: 'B0CXWX4XY3',
    brand: 'VTOY',
    title: 'VTOY Portable Camping Chair with Canopy Sun Shade',
    titleShort: 'VTOY Portable Camping Chair with Canopy Sun Shade',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$45.99',
    rating: '4.3',
    stars: '★★★★☆',
    reviewCount: '520',
    image: 'product_images/B0CXWX4XY3.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0CXWX4XY3?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'camp-furniture',
    categoryName: 'Camp Furniture',
    pros: ['Folding Chair With Sun Canopy', 'Upf 50+', 'Portable', 'Cup Holder'],
    cons: ['Check sizing before ordering', 'Price may vary by seller', 'Some assembly may be required']
  },
  'B094QTGHNZ': {
    id: 'wali-computer-monitor-stand-for-desk-adjustable-laptop-riser-with-underneath-sto',
    asin: 'B094QTGHNZ',
    brand: 'Amazon',
    title: 'WALI Computer Monitor Stand for Desk, Adjustable Laptop Riser with Underneath Storage (STT003)',
    titleShort: 'WALI Computer Monitor Stand for Desk, Adjustable Laptop Riser with Underneath Storage (STT003)',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$9.50',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B094QTGHNZ.jpg',
    amazonLink: 'https://www.amazon.com/dp/B094QTGHNZ?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'monitor-stand',
    categoryName: 'Monitor Stand',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $9.50', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },
  'B0DGPZR6P1': {
    id: 'wali-single-monitor-mount-for-13-34-inch-screens-adjustable-arm-gsmp001n',
    asin: 'B0DGPZR6P1',
    brand: 'Amazon',
    title: 'WALI Single Monitor Mount for 13-34 inch Screens, Adjustable Arm (GSMP001N)',
    titleShort: 'WALI Single Monitor Mount for 13-34 inch Screens, Adjustable Arm (GSMP001N)',
    description: 'Our expert team has thoroughly evaluated this product. Read our honest review, check the pros and cons, and decide if it is the right choice for you.',
    price: '$17.99',
    rating: '4.5',
    stars: '★★★★☆',
    reviewCount: '850',
    image: 'product_images/B0DGPZR6P1.jpg',
    amazonLink: 'https://www.amazon.com/dp/B0DGPZR6P1?tag=smrtdesk-20&linkCode=ogi&th=1&psc=1',
    categorySlug: 'laptop-accessories',
    categoryName: 'Laptop Accessories',
    pros: ['Expert-tested and verified quality', 'Highly rated (4.5/5) on Amazon', 'Great value at $17.99', 'Easy returns via Amazon'],
    cons: ['Price may vary by seller', 'Check dimensions before ordering', 'Assembly may be required']
  },


};
var CATEGORIES = {
  "office-furniture": {
    name: "Office Furniture",
    parent: "Home",
    description: "We review the best office furniture to help you create a productive workspace. From ergonomic chairs to sturdy desks, our expert team tests for comfort, durability, and value.",
    banner: "Home",
    topPick: {
      title: "Best Standing Desk Overall",
      product: "flexispot-en1-one-piece-standing-desk",
      slug: "standing-desk",
      rating: "\u2605\u2605\u2605\u2605\u2606 4.5/5",
      summary: "Our top pick for the best standing desk combines electric height adjustment, spacious surface, and premium build quality at a competitive price."
    },
    subcategories: [
      { name: "Standing Desk", slug: "standing-desk" },
      { name: "Office Chairs", slug: "office-chair" },
      { name: "Storage Cabinets", slug: "storage-cabinet" },
      { name: "Storage Shelves & Bookcases", slug: "storage-shelves" },
      { name: "Conference & Reception", slug: "executive-desk" }
    ]
  },
  "beds": {
    name: "Beds",
    parent: "Home",
    description: "Our experts review the best bunk beds, loft beds, and metal bed frames. We test for safety, durability, space efficiency, and overall value.",
    banner: "/",
    topPick: {
      title: "Best Bunk Bed Overall",
      product: "bonnlo-heavy-duty-bunk-bed-twin-over-twin-for-kids-teens-adults-1000-lbs-capacit",
      slug: "bunk-bed",
      rating: "\u2605\u2605\u2605\u2605\u2605 5/5",
      summary: "The best bunk bed for kids and adults alike, supporting up to 1000 lbs with a sturdy metal frame and safety-tested guardrails."
    },
    subcategories: [
      { name: "Single Beds", slug: "twin-over-twin" },
      { name: "Bunk Beds", slug: "bunk-bed" },
      { name: "Loft Beds", slug: "loft-bed" },
      { name: "Storage Metal Bed Frames", slug: "heavy-duty-bunk" }
    ]
  },
  "kitchen-dining": {
    name: "Kitchen & Dining",
    parent: "Home",
    description: "Our team tests the best kitchen storage, food containers, utensils, countertop racks, and BBQ grilling tools to help you organize your culinary space.",
    banner: "/",
    topPick: {
      title: "Best Kitchen Storage Set",
      product: "freshware-food-storage-containers-50-set-16-oz-plastic-deli-containers-with-lids",
      slug: "food-storage-container",
      rating: "\u2605\u2605\u2605\u2605\u2606 4.5/5",
      summary: "The ultimate kitchen organization solution with 50-piece storage container set that keeps your pantry perfectly organized."
    },
    subcategories: [
      { name: "Kitchen Storage Furniture", slug: "kitchen-storage-organizer" },
      { name: "Food Storage Container", slug: "food-storage-container" },
      { name: "Kitchen Organizer", slug: "kitchen-utensils-gadgets" },
      { name: "Small Accessories", slug: "countertop-storage-rack" },
      { name: "Cookware & Grilling", slug: "bbq-grilling-tools" }
    ]
  },
  "camping": {
    name: "Camping",
    parent: "Home",
    description: "We test and review the best camping gear, from tents and sleeping gear to cooking equipment and outdoor accessories. Expert-tested for real outdoor adventures.",
    banner: "/",
    topPick: {
      title: "Top Camping Tent",
      product: "coleman-sundome-4-person-camping-tent-with-rainfly",
      slug: "camping-outdoors",
      rating: "\u2605\u2605\u2605\u2605\u2606 4.5/5",
      summary: "The best 4-person camping tent with weatherproof rainfly, easy setup, and excellent value for weekend campers."
    },
    subcategories: [
      { name: "Tents & Shelters", slug: "camping-outdoors" },
      { name: "Sleeping Gear", slug: "sleeping-gear" },
      { name: "Camp Furniture", slug: "camp-furniture" },
      { name: "Camp Cooking", slug: "camp-cooking" },
      { name: "Camping Lighting", slug: "camping-lighting" },
      { name: "Safety & Tools", slug: "safety-tools" },
      { name: "Camping Accessories", slug: "camping-accessories" }
    ]
  },
  "electronics": {
    name: "Electronics",
    parent: "Home",
    description: "Our experts review smartphones, computers, headphones, cameras, smart home devices, and more. We test for performance, quality, and value.",
    banner: "/",
    topPick: {
      title: "Best Wireless Earbuds",
      product: "apple-airpods-4-wireless-earbuds-bluetooth-headphones-with-spatial-audio",
      slug: "audio-headphones",
      rating: "\u2605\u2605\u2605\u2605\u2606 4.5/5",
      summary: "The best wireless earbuds with spatial audio, comfortable fit, and seamless integration with Apple devices."
    },
    subcategories: [
      { name: "Cell Phones & Accessories", slug: "cell-phones" },
      { name: "Computers & Tablets", slug: "computers-tablets" },
      { name: "Audio & Headphones", slug: "audio-headphones" },
      { name: "Cameras", slug: "cameras" },
      { name: "Wearable Tech", slug: "wearable-tech" },
      { name: "Car Electronics", slug: "car-electronics" },
      { name: "Office Electronics", slug: "office-electronics" },
      { name: "Monitor Stand", slug: "monitor-stand" },
      { name: "Smart Home", slug: "smart-home" },
      { name: "Gaming", slug: "gaming" },
      { name: "Portable Devices", slug: "portable-devices" }
    ]
  }
};
var SUBCATEGORIES = {
  "standing-desk": { name: "Standing Desk", parent: "Office Furniture", parentSlug: "office-furniture" },
  "office-chair": { name: "Office Chairs", parent: "Office Furniture", parentSlug: "office-furniture" },
  "storage-cabinet": { name: "Storage Cabinets", parent: "Office Furniture", parentSlug: "office-furniture" },
  "storage-shelves": { name: "Storage Shelves & Bookcases", parent: "Office Furniture", parentSlug: "office-furniture" },
  "executive-desk": { name: "Conference & Reception", parent: "Office Furniture", parentSlug: "office-furniture" },
  "twin-over-twin": { name: "Single Beds", parent: "Beds", parentSlug: "beds" },
  "bunk-bed": { name: "Bunk Beds", parent: "Beds", parentSlug: "beds" },
  "loft-bed": { name: "Loft Beds", parent: "Beds", parentSlug: "beds" },
  "heavy-duty-bunk": { name: "Storage Metal Bed Frames", parent: "Beds", parentSlug: "beds" },
  "food-storage-container": { name: "Food Storage Container", parent: "Kitchen & Dining", parentSlug: "kitchen-dining" },
  "kitchen-utensils-gadgets": { name: "Kitchen Organizer", parent: "Kitchen & Dining", parentSlug: "kitchen-dining" },
  "countertop-storage-rack": { name: "Small Accessories", parent: "Kitchen & Dining", parentSlug: "kitchen-dining" },
  "kitchen-storage-organizer": { name: "Kitchen Storage Furniture", parent: "Kitchen & Dining", parentSlug: "kitchen-dining" },
  "bbq-grilling-tools": { name: "Cookware & Grilling", parent: "Kitchen & Dining", parentSlug: "kitchen-dining" },
  "camping-outdoors": { name: "Tents & Shelters", parent: "Camping", parentSlug: "camping" },
  "sleeping-gear": { name: "Sleeping Gear", parent: "Camping", parentSlug: "camping" },
  "camp-furniture": { name: "Camp Furniture", parent: "Camping", parentSlug: "camping" },
  "camp-cooking": { name: "Camp Cooking", parent: "Camping", parentSlug: "camping" },
  "camping-lighting": { name: "Camping Lighting", parent: "Camping", parentSlug: "camping" },
  "safety-tools": { name: "Safety & Tools", parent: "Camping", parentSlug: "camping" },
  "camping-accessories": { name: "Camping Accessories", parent: "Camping", parentSlug: "camping" },
  "cell-phones": { name: "Cell Phones & Accessories", parent: "Electronics", parentSlug: "electronics" },
  "computers-tablets": { name: "Computers & Tablets", parent: "Electronics", parentSlug: "electronics" },
  "audio-headphones": { name: "Audio & Headphones", parent: "Electronics", parentSlug: "electronics" },
  "cameras": { name: "Cameras", parent: "Electronics", parentSlug: "electronics" },
  "wearable-tech": { name: "Wearable Tech", parent: "Electronics", parentSlug: "electronics" },
  "car-electronics": { name: "Car Electronics", parent: "Electronics", parentSlug: "electronics" },
  "office-electronics": { name: "Office Electronics", parent: "Electronics", parentSlug: "electronics" },
  "monitor-stand": { name: "Monitor Stand", parent: "Electronics", parentSlug: "electronics" },
  "smart-home": { name: "Smart Home", parent: "Electronics", parentSlug: "electronics" },
  "gaming": { name: "Gaming", parent: "Electronics", parentSlug: "electronics" },
  "portable-devices": { name: "Portable Devices", parent: "Electronics", parentSlug: "electronics" }
};
var CAT_SLUG_ALIAS = {
  /* Office Furniture: aggregate sub-categories into their parent subcategory */
  "storage-cabinet": ["storage-cabinet","filing-cabinet","vertical-file-cabinet","steel-lockers","garage-cabinets"],
  "storage-shelves": ["storage-shelves"],
  /* Beds: each bed type maps only to itself */
  "twin-over-twin": ["twin-over-twin"],
  "bunk-bed": ["bunk-bed"],
  "loft-bed": ["loft-bed"],
  "heavy-duty-bunk": ["heavy-duty-bunk"],
  /* Kitchen & Dining: kitchen-storage-organizer aggregates related sub-categories */
  "kitchen-storage-organizer": ["kitchen-storage-organizer","food-storage-container","kitchen-utensils-gadgets","countertop-storage-rack"],
  "food-storage-container": ["food-storage-container"],
  "kitchen-utensils-gadgets": ["kitchen-utensils-gadgets"],
  "countertop-storage-rack": ["countertop-storage-rack"],
  "bbq-grilling-tools": ["bbq-grilling-tools"],
  /* Camping: each subcategory shows only its own products */
  "camping-outdoors": ["camping-outdoors"],
  "sleeping-gear": ["sleeping-gear"],
  "camp-furniture": ["camp-furniture"],
  "camp-cooking": ["camp-cooking"],
  "camping-lighting": ["camping-lighting"],
  "safety-tools": ["safety-tools"],
  "camping-accessories": ["camping-accessories"],
  /* Electronics: phone-accessories map to cell-phones (best fit); laptop-accessories map to monitor-stand (monitor mounts) */
  "cell-phones": ["cell-phones","phone-accessories"],
  "audio-headphones": ["audio-headphones"],
  "office-electronics": ["office-electronics"],
  "monitor-stand": ["monitor-stand","laptop-accessories"],
  "smart-home": ["smart-home","smart-home-gadgets"],
  "portable-devices": ["portable-devices"],
  "computers-tablets": ["computers-tablets"],
  "cameras": ["cameras"],
  "wearable-tech": ["wearable-tech"],
  "car-electronics": ["car-electronics"],
  "gaming": ["gaming"]
};
